### ISSUE TITLE
LWP repo moved

### ISSUE THREAD

**Issue by claudyus** [demonccc/chef-lxc-web-panel#1]
Hi @demonccc,
I just discover you chef recipes to install my LWP fork.
I like to report that the I dismiss the github pages apt repo to replace it with a packagecloud repo.

I didn't use chef by myself but if you like to update your repo the packagecloud cookbook info can be found here:
https://packagecloud.io/claudyus/LXC-Web-Panel/install#chef

**Comment by demonccc** [comment]
Hi @claudyus 

Thank you, I will check it.

Regards.
